version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git fetch --tags
    pre_install:
      - git update-index --assume-unchanged rtd_requirements.txt doc/conf.py
sphinx:
  configuration: doc/conf.py
  fail_on_warning: true
python:
  install:
    - requirements: rtd_requirements.txt
    - method: pip
      path: .
